### ISSUE TITLE
Mauvaise commande sous Linux

### ISSUE THREAD

**Issue by sltgc** [themsou/PDF4Teachers#10]
Bonjour et merci pour cette application !

**Pour info** : Sous Linux Mint 19,  mêmes soucis que@pierretravers pour le lancement constant de la licence au démarrage et ajout de -lin dans la commande + **logo non visible**, j'ai dû changer ceci en mode admin et tout fonctionne.

Sinon une idée du calendrier de la sortie des améliorations prévues (icônes grisées dans l'app) ?

**Comment by themsou** [comment]
Bonjour,

comme expliqué à @pierretraver ces problèmes vont être résolus pour la prochaine mise à jour qui devrait sortir dans quelques jours. (Le logo non visible vient aussi d'un -lin à enlever dans le lanceur).

Comme inscrit dans la documentation, la prochaine mise à jour (1.1.0) ajoutera principalement le système de notes, accompagné de quelques modifications ergonomiques et de règlements de bugs. Viendra probablement ensuite des mises à jour de correction de bugs et d'ajout de fonctionnalité simples avant la version 1.2.0, qui ajoutera des outils de PDF, comme par exemple un moyen de convertir des images en PDF etc. Enfin, la version 1.3.0 ajoutera les éléments géométriques (Flèches, rectangles etc.).

Cordialement, Clément G.
