### ISSUE TITLE
Application qui démarre toute seule au démarrage de Windows

### ISSUE THREAD

**Issue by og-edu** [themsou/PDF4Teachers#12]
bonjour et bravo pour votre travail !
comment faire pour que l'application ne se lance pas automatiquement lors d'un redémarrage du système ?
(windows 7)
merci

**Comment by themsou** [comment]
Bonjour,

PDF4Teachers ne se lance normalement pas au démarrage, je pense que vous avez dû cocher un paramètre special dans l'installer.
Tous les programmes qui se lancent au démarrage de windows sont inscrits dans l'onglet Démarrage, du gestionnaire des tâches (Sous Windows 10 et Windows 7). Vous pourrez ensuite cliquer sur Désactiver pour que l'application ne se lance plus au démarrage.
Pour accéder au gestionnaire des taches sous Windows 7, vous pouvez utiliser le raccourcis `Ctrl+Alt+Suppr`, puis cliquer sur `Gestionnaire des tâches`

Cordialement, Clément G.
