### ISSUE TITLE
Génération d'une copie PDF à partir d'images

### ISSUE THREAD

**Issue by grensv** [themsou/PDF4Teachers#13]
Actuellement nous recevons beaucoup de copies sous la forme de photos que nos élèves / étudiants nous envoient avec leur smartphone.
Peut-être PDF4Teachers inclura un jour cette fonctionnalité (besoin qui n'existait pas avant le COVID-19 !), mais en attendant, je propose une solution très efficace pour générer des PDF depuis des dossiers contenant des photos des différentes pages des copies : ceci requiert l'installation de ImageMagick + Ghostscript.

**Linux** : à adapter en fonction de votre packager : 
          > sudo apt-get install imagemagick
     Je crois que Ghostscript est installé par défaut.

**OSX** : à installer à travers brew 
          > brew install imagemagick
          > brew install ghostscript

**Windows 64 bits** , télécharger et installer avec les options par défaut :
https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs952/gs952w64.exe
https://sourceforge.net/projects/imagemagick/files/im7-exes/ImageMagick-7.0.7-25-Q8-x64-static.exe/download

_ImageMagick s'utilise en ligne de commande :_
**windows :** ouvrir un terminal de commande (cmd), aller dans le dossier des images avec la commande cd, puis par exemple :
        > magick *.jp*g -resize "2000000@>" test.pdf

Ceci a pour effet de génèrer un PDF nommé test.pdf, à partir de toutes les images .jpg ou .jpeg contenues dans le dossier, après avoir réduit les images à la taille 2Mpixels (si elles sont plus grandes). Elles sont insérées dans l’ordre alphabétique de leur nom. On peut remplacer .jpg par .png au autre selon le format des images reçues.

**Linux et OSX :** ouvrir un terminal de commande, aller dans le dossier des images avec la commande cd, puis par exemple :
        > convert *.jpg -resize 2000000@> test.pdf

sous Linux et OSX on peut remplacer *.jpg par *.pdf si on a reçu des scan page par page au format PDF mais ImageMagick n'étant pas conçu à la base pour prendre du PDF en entrée, ceci a tendance à générer un PDF visuellement un peu dégradé.

Je joins ici un script que j'ai écrit pour traiter un lot de sous dossiers, en fabriquant un pdf du nom de chaque sous-dossier. Il faut prendre soin de nommer intelligemment les sous-dossiers d’images (par exemple prénom.nom), et après c’est du velours 👍.

Exemple d’arborescence de dossiers :
_Dossier_DS_du groupe_G1_
	-> _Truc.Machin_ (sous-dossier qui contient les photos de la copie de Truc Machin)
	-> _Choupinette.Bidule_  (sous-dossier qui contient les photos de la copie de Choupinette Bidule)
	-> ….
	-> ….

Sous Windows, je propose de copier ce script dans le dossier _C:\Windows_, pour qu'il soit dans le PATH(chemin de recherche des exécutables). Sous OSX et Linux, pour qu'il soit dans le PATH, placez le dans _/usr/local/bin_ par exemple. Personnellement, je préfère me créer dans mon dossier perso un dossier _scripts_ et modifier mon PATH en éditant le fichier caché .bash_profile, en y ajoutant la ligne:
export PATH=$PATH:~/scripts

Bonne génération automatisée de PDFs !

script windows : img2pdf_lot.txt, _à renommer_ en img2pdf_lot.bat :
[img2pdf_lot.txt](https://github.com/themsou/PDF4Teachers/files/4550788/img2pdf_lot.txt)

script _OSX uniquement_ pour fusionner des pages PDF en un seul document PDF, renommer le .txt en .sh :
[mergePDF.txt](https://github.com/themsou/PDF4Teachers/files/4550820/mergePDF.txt)

**Comment by jdelmas95** [comment]
Je confirme que ce sera une fonctionnalité fort intéressante, de pouvoir sélectionner indifféremment un PDF ou une image (voire un ODT/DOC) qui serait converti immédiatement en PDF pour l'intégrer dans l'appli.

Merci en tout cas pour cette application dont je fais beaucoup de publicité sur Twitter !
