### ISSUE TITLE
Application Mac 1.1.0 corrompue

### ISSUE THREAD

**Issue by jdelmas95** [themsou/PDF4Teachers#14]
Bonjour,

Lorsque je télécharge la version **PDF4Teachers-MacOSX.dmg**, je procède à l'installation et ;ors du lancement, j'obtiens une fenêtre qui refuse le lancement : 
**« PDF4Teachers » est endommagé et ne peut pas être ouvert. Vous devriez placer cet élément dans la Corbeille.**

Problème identique avec **PDF4Teachers-MacOSX-BIN.zip**

**Comment by themsou** [comment]
Bonjour,

nous avons reproduit cette action et nous rencontrons ce problème uniquement lorsque l'application est déjà présente dans le dossier Applications, essayez de supprimer l'ancienne version avant d'installer la nouvelle.
Si cela ne fonctionne pas, cette erreur est généralement dû à une absence de signature du .dmg, mais cela ne devrait pas arriver avec la version .app (-BIN). Dans ce cas, vous pouvez nous donner votre version de Mac OS X pour que nous puissions mieux vous aider.

J'espère que nous avons réglé votre problème, Clément.

**Comment by jdelmas95** [comment]
Bonsoir,

Même en supprimant la version précédente, l'installation de la 1.10 via le DMG se passe bien, mais l'application est toujours corrompu. j'ai le même message sur iMac et MacBook Pro. Sur les deux machines je suis en MacOS Catalina 10.15.4.

**Comment by grensv** [comment]
Bonjour,

J'utilise MacOS Mojave 10.14.6, et c'est sous cet OS qu'a été compilé PDF4Teachers pour Mac. Je n'ai pour l'instant pas de moyen aisé de tester sous Catalina. Pouvez-vous vérifier que dans les _préférences -> sécurité et confidentialité_, onglet _général_ il n'y a pas un message demandant de confirmer l'autorisation d'ouvrir PDF4Teachers ? (J'assume que la coche "_Autoriser les applications téléchargées de :_"  est déjà sur "_App Store et développeurs identifiés_".

Vincent.

**Comment by jdelmas95** [comment]
Bonjour,

Je confirme qu'il s'agit bien d'une application corrompue : 
**« PDF4Teachers » est endommagé et ne peut pas être ouvert. Vous devriez placer cet élément dans la Corbeille.**

et pas d'une application non signée par un développeur connu d'Apple (message habituel rencontré avec les versions précédentes) :
**"Impossible d’ouvrir « PDF4Teachers » car le développeur ne peut pas être vérifié."**

donc, aucune application à autoriser dans Sécurité et confidentialité.

**Comment by jdelmas95** [comment]
En suivant un <a href="https://blog.vincentdeniau.fr/articles/reparer-appl-macos-endommagee">tutoriel</a> et notamment cette ligne de commande, l'application fonctionne désormais sur mes deux appareils Mac : 
`sudo su`
`xattr -rc /Applications/PDF4Teachers.app`

**Comment by grensv** [comment]
Merci jdelmas,
il y avait bien eu un problème avec l'upload des versions Mac. Nous avons ajouté dans les infos de release les sommes de contrôle sha256 des fichiers, et j'ai mis à jour les fichiers MacOSX.
Je fermerai l'issue dès que l'on est sûr qu'il n'y a plus de problèmes.
Vincent.

**Comment by cgressent** [comment]
Bonjour,
Merci pour cette nouvelle version mais j'ai exactement le même souci que les précédents utilisateurs de Mac : application corrompue même en retéléchargeant après avoir supprimé la version précédente du dossier Applications. Je suis sur Mojave.
Bonne journée,

**Comment by grensv** [comment]
Bonjour,

Que donne dans un terminal la commande shasum PDF4Teachers-MacOSX.dmg sur le fichier dmg ? (il auparavant aller dans le dossier où se trouve ce fichier avec la commande cd : typiquement > _cd ~/Downloads_ )
Les sommes de contrôle sont données dans https://github.com/themsou/PDF4Teachers/releases à la section sha256 checksums et permettent de vérifier que le fichier que j'ai uploadé est bien intègre.
Vincent.

**Comment by cgressent** [comment]
La somme de contrôle est juste (ce qui ne nous aide pas !).

Cédric

**Comment by grensv** [comment]
L'application n'est pas corrompue, mais seulement mise en quarantaine par OSX. Ceci n'arrivait pas avec les anciennes versions qui étaient packagées différement.
Merci Julien pour nous avoir aidé à découvrir le problème d'attribut de quarantaine.
**J'ai mis à jour les instructions d'installation pour Mac dans la page de Release juste au dessus des liens de téléchargement.**
On va essayer de signer la prochaine version pour ne plus avoir ce problème

**Comment by cgressent** [comment]
Bonjour,
Au risque de passer pour un pénible, le attr ne semble pas fonctionner. Cela indique « attr : command not found ».
Désolé,
Cédric

**Comment by jdelmas95** [comment]
> Bonjour, Au risque de passer pour un pénible, le attr ne semble pas fonctionner. Cela indique « attr : command not found ». Désolé, Cédric

C'est parce que ce n'est pas la commande `attr` mais :
`sudo su`
`xattr -rc /Applications/PDF4Teachers.app`

**Comment by cgressent** [comment]
OK j'ai suivi cette autre méthode et ça fonctionne ainsi. Du coup la méthode donnée dans le Releases semble incorrecte.
Merci bien :)

**Comment by grensv** [comment]
Désolé Cédric, c'est de ma faute, copier coller un peu rapide depuis mon terminal 🤬. Je viens donc de mettre à jour les notes d'installation.
Pour moi le sudo est inutile si on fait ceci dans le dossier téléchargements. Julien, si tu peux tester sur Catalina et confirmer que le sudo est inutile ça serait super.
Vincent.

**Comment by ClementGre** [comment]
Nous avons crée un rapport de bug sur la Java Bug Database, que vous pourez retrouver sur le JDK Bug System à l'adresse : [https://bugs.openjdk.java.net/browse/JDK-8254662](https://bugs.openjdk.java.net/browse/JDK-8254662).

Résoudre ce problème nous permettra de pouvoir générer le package DMG en utilisant JPackager de Java et non un outil externe qui apporte des complications et problèmes dont le bug #16 (bug mineur).

\- Clément
