### ISSUE TITLE
Icône de tri par nom inversée

### ISSUE THREAD

**Issue by jdelmas95** [themsou/PDF4Teachers#19]
Bonjour,

Petit détail : l'icône de tri par "Nom" est inversée. Cela semble aussi le cas du tri par "Dossier". En effet, lorsque l'icône ressemble à  `^`, cela signifie normalement qu'elle est triée dans l'ordre alphabétique, or elle est triée dans l'ordre inversement alphabétique.

<img width="51" alt="Capture d’écran 2020-05-03 à 12 46 35" src="https://user-images.githubusercontent.com/32643240/80912306-5a413b00-8d3c-11ea-9a87-3053c3c6cdcb.png">

Merci

**Comment by grensv** [comment]
Tout à fait juste, l'icône ne respectait pas les conventions usuelles. Sera pris en compte dans la 1.1.1
