### ISSUE TITLE
Application Mac 1.1.0 corrompue

### ISSUE THREAD

**Issue by pplokarz** [themsou/PDF4Teachers#21]
Je viens d'essayer de faire la mise à jour comme suggéré à l'ouverture. Il m'est indiqué 'pdf4teachers est endommagé et ne peut être ouvert. Vous devriez placer cet élément dans la corbeille". La version 1.0.3 n'est-elle plus disponible ? Merci
<img width="418" alt="Capture d’écran 2020-05-05 à 09 33 53" src="https://user-images.githubusercontent.com/64831316/81043936-8fbc6480-8eb3-11ea-8ac9-e0a49cbb2d48.png">

**Comment by grensv** [comment]
Bonjour,
Depuis le changement d'outils de build avec la 1.1.0, nous avons ce problème sous Mac que j'essaye de résoudre. Dans l'Issue https://github.com/themsou/PDF4Teachers/issues/14#issuecomment-623089218, Jdelmas95 a proposé cette solution temporaire :

> En suivant un <a href="https://blog.vincentdeniau.fr/articles/reparer-appl-macos-endommagee">tutoriel</a> et notamment cette ligne de commande, l'application fonctionne désormais sur mes deux appareils Mac : 
> `sudo su`
> `xattr -rc /Applications/PDF4Teachers.app`
> 
> _Originally posted by @jdelmas95 in https://github.com/themsou/PDF4Teachers/issues/14#issuecomment-623089218_

**Comment by pplokarz** [comment]
Merci j essaierai a midi, la j ai 2h de classe virtuelle.  nul doute que cela fonctionne si ca vient de Julien 😉. Merci pour votre réponse rapide.

Envoyé de mon iPhone

**Comment by grensv** [comment]
Si vraiment besoin, les anciennes versions sont bien sûr encore disponibles (mais je ne les conseille pas) : 
https://github.com/themsou/PDF4Teachers/releases/tag/1.0.3, et cliquer sur _assets_

**Comment by pplokarz** [comment]
Oui je venais de remettre la main dessus,mais  je vais attendre si vous le conseillez, y a pas de pb


--
Peggy Plokarz
Professeur de Physique Chimie
Lycée Vauban - Brest
Mél : peggy.plokarz1@ac-rennes.fr

**Comment by pplokarz** [comment]
Bonjour, je viens seulement de faire l’essai avec le tuto de jdelmas95 mais cela ne fonctionne pas sur ma machine Catalina 10.15.4. 


Si vous pouviez me dire si je me suis trompée qq part... 
Merci,

--
Peggy Plokarz
Professeur de Physique Chimie
Lycée Vauban - Brest
Mél : peggy.plokarz1@ac-rennes.fr

**Comment by pplokarz** [comment]
> Bonjour, je viens seulement de faire l’essai avec le tuto de jdelmas95 mais cela ne fonctionne pas sur ma machine Catalina 10.15.4. <img width="591" alt="Capture d’écran 2020-05-08 à 09 29 07" src="https://user-images.githubusercontent.com/64831316/81382939-7e6f9400-910f-11ea-834b-a212344113c4.png"> Si vous pouviez me dire si je me suis trompée qq part... Merci,
> […](#)

Je n'avais pas pris le fichier téléchargé mardi denier...  ...package .dmg  
Tout est bon maintenant   !
