### ISSUE TITLE
Avertissement lors de l'exportation du barème vers autres copies

### ISSUE THREAD

**Issue by grensv** [themsou/PDF4Teachers#22]
Suggestion à nous même, à débattre :
Si on veut changer le barème (formatage par exemple) en cours de correction, et que l'on fait exporter vers toutes les autres copies (pour éviter de modifier à chaque fois, et d'aller modifier les copies déjà corrigées), ON PERD LA NOTATION déjà saisie et sans AVERTISSEMENT => il manque un warning, ou des options (conserver les notes déjà saisies, exporter uniquement le formattage...)

**Comment by themsou** [comment]
Ce "bug" a été résolu avec le bug #20. Si un note de l'ancien barème comporte le même nom et les mêmes parents, la note du nouveau barème prendra la position sur le PDF et la valeur de la note de l'ancien barème.

Clément G.
