### ISSUE TITLE
Interface saisie notes

### ISSUE THREAD

**Issue by grensv** [themsou/PDF4Teachers#23]
Suggestion à nous même à débattre :
- Quand on valide un champ de note avec touche entrée, passer au suivant (onglet) ou fermer le pop-up (menu contextuel)
- Dans le menu contextuel avec la prochaine note à saisir, proposer les 2 ou 3 prochaines ? Ou bien uniquement la prochaine mais avec un bouton de liste à sa gauche qui permet d'avoir les suivantes ? A noter que dans la 1.1.0, lorsque le pointeur survole la zone note du menu contextuel ceci désélectionne le champ de saisie, ce qui fait perdre du temps.
- Le point d'insertion de la note dépend du dernier clic, et quand on doit reselectionner le champ de saisie dans le menu contextuel, ceci déplace le point d'insertion. Il faudrait mémoriser la position du clic droit d'ouverture du menu contextuel pour le point d'insertion.
- Lorsque que l'on se place très à gauche pour le clic contextuel, il semble qu'il y ait un décalage vers la droite du point d'insertion comme si il y avait une position x minimum. C'est logique si on clic en dehors de la page, mais cette distance devrait être < 1/30ème de la largeur.

**Comment by themsou** [comment]
Le premier et dernier point mentionné ont été réglés. Cela a donc en partie réglé le point 3 qui, même quand on clique sur le champ, ne se reproduit plus (seulement dans certaines conditions).
Quand au point 2, ceci serait trop compliqué à développer, ça demanderait de revoir la manière de récupérer l'élément suivant sur la page. De plus, comme convenu, cela serait trop encombrant pour l'utilisateur.

     Clément G.
