### ISSUE TITLE
Sauvegarde du formatage du barème dans l'édition

### ISSUE THREAD

**Issue by grensv** [themsou/PDF4Teachers#26]
Actuellement les réglages de la fenêtre de formatage des notes ne sont pas enregistrés dans le barème dans le fichier d'édition.
Donc si des éditions ont été déjà faites sur plusieurs copies, et que pour une copie il est nécessaire de changer le formatage du barème, on peut avoir le problème suivant (ceci m'est arrivé à cause d'un PDF mal scanné, avec un format paysage A3, qui requerrait de diminuer la taille des polices des commentaires et des notes) :
- Lorsque l'on rouvre un fichier déjà édité, les tailles des notes sont modifiées par le réglage en cours
- Lors de l'exportation c'est la valeur des réglages en cours qui est prise en en compte, donc toutes les éditions qui ont besoin d'un autre réglage sont mal exportées => on est obligé de faire l'exportation en plusieurs fois.

**Comment by themsou** [comment]
Après le réglage du bug des dimensions des pages non respectés dans certains cas, cette fonctionnalité perds son utilité, ce serait ajouter beaucoup de complexité au système de notes pour pas grand chose : une fois notre style définis, celui-ci reste le même sur toutes les copies et même sur tous les devoirs, peut-être quelques modifications au niveau de l'affichage du nom de la note mais sans plus. À voir ce que les autres personnes pensent de l'ajout de cette fonctionnalité, mais elle risque de devenir lourde pour les utilisateurs.

Clément G.
