### ISSUE TITLE
Fonctionnalité souhaitée : Modification d'un élément favori

### ISSUE THREAD

**Issue by grensv** [themsou/PDF4Teachers#4]
Il serait bien de pouvoir modifier les propriétés d'un élément favori (taille police, couleur...)

**Comment by grensv** [comment]
En attendant on peut faire :
- insérer l'élément depuis les favoris
- modifier les propriétés qu'on veut changer
- clic droit sur l'élément dans la page, -> ajouter aux favoris
- dans les favoris, clic droit sur l'ancien élément -> retirer

**Comment by themsou** [comment]
Bonjour,

Il serait trop compliqué de pouvoir modifier l'élément directement depuis un menu contextuel, mais j'ai ajouté une fonction qui permet d'ajouter l'élément et de le lier automatiquement avec l'élément ajouté (Clic droit -> Ajouter et lier).

Cette fonction va permettre de modifier l'élément favoris sans avoir à le remplacer, car tout changement apporté à l'élément de l'édition entrainera une modification de l'élément de la liste (Principe du lien entre élément de liste et élément d'édition).

J'espère que cet ajout vous conviendra.

Cordialement, Clément G.
