### ISSUE TITLE
Fonctionnalité souhaité : regrouper les éléments favoris par thèmes

### ISSUE THREAD

**Issue by cdaudet** [themsou/PDF4Teachers#6]
Bonjour,
Merci pour cette version 1.0.3 qui est vraiment efficace ! 
Serait-t'il possible d'envisager dans le futur de pouvoir créer des catégories ou des thèmes dans les éléments favoris ?

Merci beaucoup !
Coralie D

**Comment by themsou** [comment]
Bonjour,

j'ai reçu beaucoup de demandes pour cette fonctionnalité, présenté sous différentes formes.
Je ne sais pas si vous souhaitez avoir des catégories pour différencier différents types de commentaires, par exemple "Commentaires d'appréciations", "Commentaires d'erreurs", "Commentaires positifs". Ou si c'est plutôt pour différencier les commentaires de différents devoirs.

Créer des sous-catégories dans Favoris aurait été assez compliqué et encombrant pour les utilisateurs et la majorité des personnes qui demandaient cette fonctionnalité la souhaitait pour différencier les commentaires des différents devoirs.

Je suis donc partis sur un autre format, à partir de la version 1.1.0, vous pourrez enregistrer vos éléments favoris dans une liste, cela vous permettra d'avoir plusieurs listes d'éléments favoris que vous aurez enregistrés. Vous pourrez ensuite les charger quand vous le souhaiteriez.

J'espère que cette fonctionnalité vous conviendra.
Cordialement, Clément G.
