### ISSUE TITLE
license qui réapparaît à chaque lancement

### ISSUE THREAD

**Issue by pierretravers** [themsou/PDF4Teachers#9]
Bonjour.
Sous Linux
La license réapparaît à chaque lancement.

**Comment by themsou** [comment]
Bonjour,

La license apparait lors du premier démarrage. Pour détecter si l'application est à son premier démarrage, elle vérifie si le fichier `settings.yml`, situé dans `<Votre dossier d'utilisateur>/.PDF4TEachers/` existe bien. Il se peut donc que l'application n'ait pas réussi à écrire ce fichier.

Vérifiez que ce fichier existe bien, s'il n'existe pas, vérifiez que l'application n'a pas les droits d'écriture pour ce dossier (Vous pouvez vérifier dans la console).
Vérifiez que vos éditions s'enregistrent bien, si l'application n'a pas les droits d'écriture, ce ne devrait pas être le cas.
Dans le cas inverse, il se peut que ceci soit lié à la compilation Linux qui n'aurait pas été faite correctement. Dans ce cas, vous pouvez m'envoyer le contenu de la console (terminal de commande), en ouvrant l'application avec ce dernier.

J'espère que vous arriverez à résoudre votre problème.
- Clément G.

**Comment by pierretravers** [comment]
Bonjour.
Oui le fichier existe bien et il est modifié lors de la fermeture du soft apparemmment.
Dans le terminal, j'obtiens ça :

> Apr 28, 2020 8:00:17 AM org.apache.fontbox.ttf.GlyfCompositeDescript getPointCount
GRAVE: GlyphDescription for index 15 is null, returning 0

(java:5689): Gdk-WARNING **: 08:00:17.258: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
Apr 28, 2020 8:00:17 AM org.apache.fontbox.ttf.GlyfCompositeDescript getPointCount
GRAVE: GlyphDescription for index 15 is null, returning 0
Apr 28, 2020 8:00:19 AM org.apache.fontbox.ttf.GlyfCompositeDescript getPointCount
GRAVE: GlyphDescription for index 7 is null, returning 0
  
Merci encore et bravo pour ce chouette soft !

**Comment by themsou** [comment]
Bonjour,
En effet, il s'agissait d'un problème lors de la vérification du fichier, le problème a été réglé, il sera effectif dans la prochaine mise à jour qui devrais sortir dans quelques jours.

 -Clément G.
